CREATE TABLE [dbo].[Accounts]
(
	[AccountId] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[UserObjectId] UNIQUEIDENTIFIER NOT NULL,
	[AccountNum] INT NOT NULL,
	[IsActive] BIT DEFAULT 0 NOT NULL,
	--CONSTRAINT [FK_Accounts_Users] FOREIGN KEY ([UserId]) REFERENCES [Users]([UserId]) ON DELETE NO ACTION
)
