CREATE TABLE [dbo].[Receipts]
(
	[ReceiptId] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[UserObjectId] UNIQUEIDENTIFIER,
	[DateTime] DATETIME DEFAULT CURRENT_TIMESTAMP,
	[IsScanned] BIT DEFAULT 0,
	[StoreId] INT,
	[ImageId] VARCHAR(MAX),
	CONSTRAINT [FK_Receipts_Stores] FOREIGN KEY ([StoreId]) REFERENCES [Stores]([StoreId]) ON DELETE SET NULL
)
