CREATE TABLE [dbo].[Receipts]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[UserId] INT,
	[DateTime] DATETIME DEFAULT CURRENT_TIMESTAMP,
	[IsScanned] BIT DEFAULT 0,
	[StoreId] INT NOT NULL,
	CONSTRAINT [FK_Receipts_Users] FOREIGN KEY ([UserId]) REFERENCES [Users] ([Id]) ON DELETE CASCADE
)
