CREATE TABLE [dbo].[Receipts]
(
	[ReceiptId] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[UserObjectId] UNIQUEIDENTIFIER,
	[DateTime] DATETIME DEFAULT CURRENT_TIMESTAMP,
	[IsScanned] BIT DEFAULT 0,
	[StoreId] INT NOT NULL,
	[ImageId] VARCHAR(MAX)
)
